# Generated by Django 5.2.17 on 2026-09-23 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CsmOffice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='e.g. CRK (used as transaction prefix)', max_length=10, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('qr_issued_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CSM Office',
                'verbose_name_plural': 'CSM Offices',
                'db_table': 'csm_office',
                'ordering': ['name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CsmResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ctms_transaction_id', models.BigIntegerField(db_index=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'CSM Response',
                'verbose_name_plural': 'CSM Responses',
                'db_table': 'csm_csmresponse',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CsmService',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0, help_text='DOLE CSF Form No. 3 order')),
            ],
            options={
                'verbose_name': 'CSM Service',
                'verbose_name_plural': 'CSM Services',
                'db_table': 'csm_service',
                'ordering': ['sort_order', 'name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CtmsCounter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Window 1, Window 2', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counters', to='ctms.csmoffice')),
            ],
            options={
                'verbose_name': 'CTMS Counter',
                'verbose_name_plural': 'CTMS Counters',
                'db_table': 'ctms_counter',
                'ordering': ['office', 'name'],
                'unique_together': {('office', 'name')},
            },
        ),
        migrations.CreateModel(
            name='CtmsStaffOffice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='ctms.csmoffice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_offices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'CTMS Staff Office',
                'verbose_name_plural': 'CTMS Staff Offices',
                'db_table': 'ctms_staff_office',
                'unique_together': {('user', 'office')},
            },
        ),
        migrations.CreateModel(
            name='CtmsTransaction',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_no', models.CharField(db_index=True, max_length=24, unique=True)),
                ('queue_date', models.DateField(db_index=True, help_text='Local Manila date')),
                ('queue_seq', models.PositiveIntegerField()),
                ('queue_no', models.CharField(help_text='e.g. 042 or P-007', max_length=8)),
                ('is_priority', models.BooleanField(default=False, help_text='Senior / PWD / Pregnant')),
                ('client_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving'), ('done', 'Done'), ('no_show', 'No-show'), ('cancelled', 'Cancelled')], db_index=True, default='waiting', max_length=12)),
                ('source', models.CharField(choices=[('qr', 'QR Check-in'), ('kiosk', 'Kiosk'), ('staff', 'Staff Walk-in')], default='qr', max_length=10)),
                ('checked_in_at', models.DateTimeField(db_index=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('done_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('ticket_token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('survey_token', models.CharField(db_index=True, max_length=32, unique=True)),
                ('claim_code', models.CharField(max_length=4)),
                ('counter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='ctms.ctmscounter')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ctms.csmoffice')),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_transactions', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='ctms.csmservice')),
            ],
            options={
                'verbose_name': 'CTMS Transaction',
                'verbose_name_plural': 'CTMS Transactions',
                'db_table': 'ctms_transaction',
                'ordering': ['-checked_in_at'],
                'indexes': [models.Index(fields=['office', 'status', 'queue_date'], name='ctms_transa_office__bd142f_idx'), models.Index(fields=['checked_in_at'], name='ctms_transa_checked_2dd350_idx')],
                'unique_together': {('office', 'queue_date', 'queue_seq')},
            },
        ),
    ]
