# Generated by Django 5.2.17 on 2026-09-24 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ctmstransaction',
            name='assigned_personnel',
            field=models.CharField(blank=True, help_text='Designated personnel / officer', max_length=200, null=True),
        ),
    ]
