# Generated by Django 5.2.17 on 2026-09-23 08:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(db_index=True, help_text='e.g. RO3, BUL, PAM', max_length=20, unique=True)),
                ('slug', models.SlugField(help_text='URL-safe slug e.g. ro3, bulacan', unique=True)),
                ('office_type', models.CharField(choices=[('REGIONAL', 'Regional Office'), ('PROVINCIAL', 'Provincial Office'), ('SATELLITE', 'Satellite Office')], default='PROVINCIAL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Office',
                'verbose_name_plural': 'Offices',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('pct_minutes', models.PositiveIntegerField(help_text="Target processing cycle time in minutes (Citizen's Charter)")),
                ('classification', models.CharField(choices=[('SIMPLE', 'Simple (<= 3 days)'), ('COMPLEX', 'Complex (<= 7 days)'), ('HIGHLY_TECHNICAL', 'Highly Technical (<= 20 days)')], default='SIMPLE', max_length=20)),
                ('directions_override', models.TextField(blank=True, help_text='Optional override for unit directions')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('service_date', models.DateField(db_index=True)),
                ('queue_number', models.CharField(db_index=True, help_text='e.g. 014', max_length=10)),
                ('transaction_number', models.CharField(db_index=True, help_text='e.g. RO3-260923-014', max_length=32, unique=True)),
                ('verification_code', models.CharField(help_text='Manual fallback code for CSM survey', max_length=4)),
                ('client_name', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_number', models.CharField(blank=True, max_length=30)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('source', models.CharField(choices=[('SELF_SERVICE', 'Self Service (Client Mobile)'), ('FRONT_DESK', 'Front Desk (PACD)')], default='SELF_SERVICE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_tickets', to=settings.AUTH_USER_MODEL)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='queueing.office')),
            ],
            options={
                'verbose_name': 'Queue Ticket',
                'verbose_name_plural': 'Queue Tickets',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. TSSD-LRLS, TSSD-EW, MALSU, IMSD', max_length=200)),
                ('code', models.CharField(help_text='e.g. LRLS, EW', max_length=50)),
                ('directions', models.TextField(blank=True, help_text='e.g. 2nd floor, right side')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='queueing.office')),
            ],
            options={
                'verbose_name': 'Unit',
                'verbose_name_plural': 'Units',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TicketItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pct_minutes_snapshot', models.PositiveIntegerField(help_text='Target PCT copied from service on creation')),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SERVING', 'Serving'), ('DONE', 'Done'), ('SKIPPED', 'Skipped')], db_index=True, default='WAITING', max_length=20)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('survey_submitted_at', models.DateTimeField(blank=True, help_text='Set ONLY by CSM survey system', null=True)),
                ('served_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='served_ticket_items', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_items', to='queueing.service')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='queueing.queueticket')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ticket_items', to='queueing.unit')),
            ],
            options={
                'verbose_name': 'Ticket Item',
                'verbose_name_plural': 'Ticket Items',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_profiles', to='queueing.office')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queueing_profile', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='queueing.unit')),
            ],
            options={
                'verbose_name': 'Staff Profile',
                'verbose_name_plural': 'Staff Profiles',
            },
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='queueing.unit'),
        ),
        migrations.CreateModel(
            name='QueueCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField(db_index=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_counters', to='queueing.office')),
            ],
            options={
                'verbose_name': 'Queue Counter',
                'verbose_name_plural': 'Queue Counters',
                'constraints': [models.UniqueConstraint(fields=('office', 'service_date'), name='unique_office_service_date')],
            },
        ),
        migrations.AddConstraint(
            model_name='queueticket',
            constraint=models.UniqueConstraint(fields=('office', 'service_date', 'queue_number'), name='unique_office_date_queue_number'),
        ),
        migrations.AddIndex(
            model_name='ticketitem',
            index=models.Index(fields=['unit', 'status'], name='idx_unit_status'),
        ),
        migrations.AddConstraint(
            model_name='ticketitem',
            constraint=models.UniqueConstraint(fields=('ticket', 'service'), name='unique_ticket_service'),
        ),
    ]
